# Generated by Django 5.1.1 on 2024-09-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Salary',
            field=models.IntegerField(),
        ),
    ]
