# Generated by Django 5.1.1 on 2024-09-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
